### ISSUE TITLE
New Input Screen - Greyed Out

### ISSUE THREAD

**Issue by srileyt3** [Cisco-AMP/amp4e_splunk_events_input#34]
I've downloaded v 1.1.7 from Splunkbase.
I am able to input the API ClientID and Key.

When navigating to New Input, all entry boxes and drop-downs are greyed out.

The internal Splunk Web service, access and access_ui logs refer to the following error:

error:321 - Masking the original 404 message: 'The path '/en-US/custom/amp4e_events_input/amp_streams_api_controller/groups_list' was not found.' with 'Page not found!' for security reasons

I am able to use the API creds to test via curl from the command line of the Heavy Forwarder.

Any ideas?

**Comment by spodda01** [comment]
Hi, Did you find a solution ?

**Comment by samsonnguyen** [comment]
hello, i found that this happens when attempting to use a read-only api key.

As per the documentation on Splunkbase, a pre-req to using this app is to have an AMP for Endpoints read-write key.

This app needs to make a POST request to v1/event_streams, and hence requires a read-write key to manage the server side (AMP for Endpoints) streams.
